spring:
  application:
    name:
      givetree

  profiles:
    include: finance, local

  config:
    import: classpath:/properties/application-secret.yml

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true
