spring:
  application:
    name:
      givetree
  profiles:
    include: finance, local, blockchain, firebase

  config:
    import:
      - classpath:/properties/application-secret.yml
      - classpath:/properties/application-oauth.yml

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        discriminator:
          ignore_explicit_for_joined: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
